config/routes.rb
Rails.application.routes.draw do
  resources :wine_strains
  resources :strains
  resources :wines
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/strain.rb
class Strain < ApplicationRecord
    has_many :wine_strains
    has_many :wines, through: :wine_strains

end

app/models/wine.rb
class Wine < ApplicationRecord
    has_many :wine_strains
    has_many :strains, through: :wine_strains

end

app/models/wine_strain.rb
class WineStrain < ApplicationRecord
  belongs_to :wine
  belongs_to :strain
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/strains_controller.rb
class StrainsController < ApplicationController
  before_action :set_strain, only: [:show, :edit, :update, :destroy]

  # GET /strains
  # GET /strains.json
  def index
    @strains = Strain.all
  end

  # GET /strains/1
  # GET /strains/1.json
  def show
  end

  # GET /strains/new
  def new
    @strain = Strain.new
  end

  # GET /strains/1/edit
  def edit
  end

  # POST /strains
  # POST /strains.json
  def create
    @strain = Strain.new(strain_params)

    respond_to do |format|
      if @strain.save
        format.html { redirect_to @strain, notice: 'Strain was successfully created.' }
        format.json { render :show, status: :created, location: @strain }
      else
        format.html { render :new }
        format.json { render json: @strain.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /strains/1
  # PATCH/PUT /strains/1.json
  def update
    respond_to do |format|
      if @strain.update(strain_params)
        format.html { redirect_to @strain, notice: 'Strain was successfully updated.' }
        format.json { render :show, status: :ok, location: @strain }
      else
        format.html { render :edit }
        format.json { render json: @strain.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /strains/1
  # DELETE /strains/1.json
  def destroy
    @strain.destroy
    respond_to do |format|
      format.html { redirect_to strains_url, notice: 'Strain was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_strain
      @strain = Strain.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def strain_params
      params.require(:strain).permit(:name)
    end
end

app/controllers/wine_strains_controller.rb
class WineStrainsController < ApplicationController
  before_action :set_wine_strain, only: [:show, :edit, :update, :destroy]

  # GET /wine_strains
  # GET /wine_strains.json
  def index
    @wine_strains = WineStrain.all
  end

  # GET /wine_strains/1
  # GET /wine_strains/1.json
  def show
  end

  # GET /wine_strains/new
  def new
    @wine_strain = WineStrain.new
  end

  # GET /wine_strains/1/edit
  def edit
  end

  # POST /wine_strains
  # POST /wine_strains.json
  def create
    @wine_strain = WineStrain.new(wine_strain_params)

    respond_to do |format|
      if @wine_strain.save
        format.html { redirect_to @wine_strain, notice: 'Wine strain was successfully created.' }
        format.json { render :show, status: :created, location: @wine_strain }
      else
        format.html { render :new }
        format.json { render json: @wine_strain.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /wine_strains/1
  # PATCH/PUT /wine_strains/1.json
  def update
    respond_to do |format|
      if @wine_strain.update(wine_strain_params)
        format.html { redirect_to @wine_strain, notice: 'Wine strain was successfully updated.' }
        format.json { render :show, status: :ok, location: @wine_strain }
      else
        format.html { render :edit }
        format.json { render json: @wine_strain.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /wine_strains/1
  # DELETE /wine_strains/1.json
  def destroy
    @wine_strain.destroy
    respond_to do |format|
      format.html { redirect_to wine_strains_url, notice: 'Wine strain was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_wine_strain
      @wine_strain = WineStrain.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def wine_strain_params
      params.require(:wine_strain).permit(:wine_id, :strain_id)
    end
end

app/controllers/wines_controller.rb
class WinesController < ApplicationController
  before_action :set_wine, only: [:show, :edit, :update, :destroy]

  # GET /wines
  # GET /wines.json
  def index
    @wines = Wine.all
  end

  # GET /wines/1
  # GET /wines/1.json
  def show
  end

  # GET /wines/new
  def new
    @wine = Wine.new
  end

  # GET /wines/1/edit
  def edit
  end

  # POST /wines
  # POST /wines.json
  def create
    @wine = Wine.new(name: wine_params[:name])
    respond_to do |format|
      if @wine.save
        wine_params[:strain_ids].reject(&:empty?).each_with_index do |id, index|
          WineStrain.create!(wine_id: @wine.id, strain_id: id, percentage: wine_params[:percentages][index])
        end
        format.html { redirect_to @wine, notice: 'Wine was successfully created.' }
        format.json { render :show, status: :created, location: @wine }
      else
        format.html { render :new }
        format.json { render json: @wine.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /wines/1
  # PATCH/PUT /wines/1.json
  def update
    respond_to do |format|
      if @wine.update(wine_params)
        format.html { redirect_to @wine, notice: 'Wine was successfully updated.' }
        format.json { render :show, status: :ok, location: @wine }
      else
        format.html { render :edit }
        format.json { render json: @wine.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /wines/1
  # DELETE /wines/1.json
  def destroy
    @wine.destroy
    respond_to do |format|
      format.html { redirect_to wines_url, notice: 'Wine was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_wine
      @wine = Wine.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def wine_params
      params.require(:wine).permit(:name, strain_ids: [], percentages: [])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/strains_helper.rb
module StrainsHelper
end

app/helpers/wine_strains_helper.rb
module WineStrainsHelper
end

app/helpers/wines_helper.rb
module WinesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cepas</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/strains/_form.html.erb
<%= form_with(model: strain, local: true) do |form| %>
  <% if strain.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(strain.errors.count, "error") %> prohibited this strain from being saved:</h2>

      <ul>
        <% strain.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/strains/edit.html.erb
<h1>Editing Strain</h1>

<%= render 'form', strain: @strain %>

<%= link_to 'Show', @strain %> |
<%= link_to 'Back', strains_path %>

app/views/strains/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Strains</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @strains.each do |strain| %>
      <tr>
        <td><%= strain.name %></td>
        <td><%= link_to 'Show', strain %></td>
        <td><%= link_to 'Edit', edit_strain_path(strain) %></td>
        <td><%= link_to 'Destroy', strain, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Strain', new_strain_path %>

app/views/strains/new.html.erb
<h1>New Strain</h1>

<%= render 'form', strain: @strain %>

<%= link_to 'Back', strains_path %>

app/views/strains/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @strain.name %>
</p>

<%= link_to 'Edit', edit_strain_path(@strain) %> |
<%= link_to 'Back', strains_path %>

app/views/wine_strains/_form.html.erb
<%= form_with(model: wine_strain, local: true) do |form| %>
  <% if wine_strain.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(wine_strain.errors.count, "error") %> prohibited this wine_strain from being saved:</h2>

      <ul>
        <% wine_strain.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :wine_id %>
    <%= form.text_field :wine_id %>
  </div>

  <div class="field">
    <%= form.label :strain_id %>
    <%= form.text_field :strain_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/wine_strains/edit.html.erb
<h1>Editing Wine Strain</h1>

<%= render 'form', wine_strain: @wine_strain %>

<%= link_to 'Show', @wine_strain %> |
<%= link_to 'Back', wine_strains_path %>

app/views/wine_strains/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Wine Strains</h1>

<table>
  <thead>
    <tr>
      <th>Wine</th>
      <th>Strain</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @wine_strains.each do |wine_strain| %>
      <tr>
        <td><%= wine_strain.wine_id %></td>
        <td><%= wine_strain.strain_id %></td>
        <td><%= link_to 'Show', wine_strain %></td>
        <td><%= link_to 'Edit', edit_wine_strain_path(wine_strain) %></td>
        <td><%= link_to 'Destroy', wine_strain, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Wine Strain', new_wine_strain_path %>

app/views/wine_strains/new.html.erb
<h1>New Wine Strain</h1>

<%= render 'form', wine_strain: @wine_strain %>

<%= link_to 'Back', wine_strains_path %>

app/views/wine_strains/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Wine:</strong>
  <%= @wine_strain.wine_id %>
</p>

<p>
  <strong>Strain:</strong>
  <%= @wine_strain.strain_id %>
</p>

<%= link_to 'Edit', edit_wine_strain_path(@wine_strain) %> |
<%= link_to 'Back', wine_strains_path %>

app/views/wines/_form.html.erb
<%= form_with(model: wine, local: true) do |form| %>
  <% if wine.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(wine.errors.count, "error") %> prohibited this wine from being saved:</h2>

      <ul>
        <% wine.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :tags %>
      <%= form.collection_check_boxes(:strain_ids,
                                      Strain.all,
                                      :id,
                                      :name) do |b| %>
      <%= b.label class:"label-checkbox" do%>
        <%=b.check_box + b.text%>
        <%= form.text_field '', name: 'wine[percentages][]' %>
      <%end%>
    <% end %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/wines/edit.html.erb
<h1>Editing Wine</h1>

<%= render 'form', wine: @wine %>

<%= link_to 'Show', @wine %> |
<%= link_to 'Back', wines_path %>

app/views/wines/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Wines</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @wines.each do |wine| %>
      <tr>
        <td><%= wine.name %></td>
        <td><%= wine.strains.pluck(:name).join(', ') %></td>
        <td><%= link_to 'Show', wine %></td>
        <td><%= link_to 'Edit', edit_wine_path(wine) %></td>
        <td><%= link_to 'Destroy', wine, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Wine', new_wine_path %>

app/views/wines/new.html.erb
<h1>New Wine</h1>

<%= render 'form', wine: @wine %>

<%= link_to 'Back', wines_path %>

app/views/wines/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @wine.name %>
</p>

<%= link_to 'Edit', edit_wine_path(@wine) %> |
<%= link_to 'Back', wines_path %>